#!/usr/bin/env bash
#
# Installs the mlx-swift SwiftPM mirror into a package or Xcode project.
#
# TTSMLX depends on the background-safe fil-technology/mlx-swift fork, while
# mlx-audio-swift and ml-explore's mlx-swift-lm both declare upstream. Upstream
# publishes the same version tags, so SwiftPM resolves the shared `mlx-swift`
# identity to whichever URL it meets first — and the build succeeds either way,
# silently missing the Metal patch that keeps the app alive when iOS revokes
# GPU access on backgrounding.
#
# Mirrors apply to the ROOT package, so every consuming app needs its own copy;
# a mirror inside TTSMLX only helps when TTSMLX itself is the root.
#
# Usage:
#   Tools/install-mirrors.sh                      # current directory (SwiftPM package)
#   Tools/install-mirrors.sh path/to/App.xcodeproj
#
# Verify afterwards with Tools/verify-mlx-fork.sh.

set -euo pipefail

source_file="$(cd "$(dirname "$0")" && pwd)/mlx-swift-mirrors.json"
target="${1:-.}"

if [[ "$target" == *.xcodeproj ]]; then
    dest="$target/project.xcworkspace/xcshareddata/swiftpm/configuration"
else
    dest="$target/.swiftpm/configuration"
fi

mkdir -p "$dest"
cp "$source_file" "$dest/mirrors.json"
echo "installed mirror -> $dest/mirrors.json"
echo "note: an .xcodeproj generated by XcodeGen is rebuilt from project.yml,"
echo "      so re-run this after regenerating the project."
